# Generated by Django 3.2.9 on 2021-11-07 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0009_auto_20211107_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_set', to=settings.AUTH_USER_MODEL, verbose_name='Количество лайков вопроса'),
        ),
    ]
