# Generated by Django 3.2.9 on 2021-11-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_alter_question_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Описание вопроса'),
        ),
    ]
