# Generated by Django 3.2.9 on 2021-11-09 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0013_userquestionrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquestionrelation',
            options={'verbose_name': 'Отношение', 'verbose_name_plural': 'Отношения'},
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_question', to=settings.AUTH_USER_MODEL, verbose_name='Автор вопроса'),
        ),
        migrations.AlterField(
            model_name='userquestionrelation',
            name='in_bookmarks',
            field=models.BooleanField(default=False, verbose_name='Закладки'),
        ),
        migrations.AlterField(
            model_name='userquestionrelation',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='userquestionrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='userquestionrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
