# Generated by Django 3.2.9 on 2021-11-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0014_auto_20211109_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], null=True, verbose_name='Оценка'),
        ),
    ]
