# Generated by Django 3.2.9 on 2021-11-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0015_alter_userquestionrelation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг вопроса'),
        ),
    ]
